src/Entity/Room.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RoomRepository")
 * @Vich\Uploadable
 */
class Room
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    public $id;
    public function __toString()
    {
        return (string) $this->getId();
    }
    /**
     * @ORM\Column(type="string", length=255)
     */
    public $room_name;

    /**
     * @ORM\Column(type="float")
     */
    public $room_price;

    /**
     * @ORM\Column(type="integer")
     */
    public $room_person_amount;

    /**
     * @ORM\Column(type="boolean")
     */
    private $availability;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRoomName(): ?string
    {
        return $this->room_name;
    }

    public function setRoomName(string $room_name): self
    {
        $this->room_name = $room_name;

        return $this;
    }

    public function getRoomPrice(): ?float
    {
        return $this->room_price;
    }

    public function setRoomPrice(float $room_price): self
    {
        $this->room_price = $room_price;

        return $this;
    }

    public function getRoomPersonAmount(): ?int
    {
        return $this->room_person_amount;
    }

    public function setRoomPersonAmount(int $room_person_amount): self
    {
        $this->room_person_amount = $room_person_amount;

        return $this;
    }

    public function getAvailability(): ?bool
    {
        return $this->availability;
    }

    public function setAvailability(bool $availability): self
    {
        $this->availability = $availability;

        return $this;
    }
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="room", fileNameProperty="imageName", size="imageSize")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer")
     *
     * @var integer
     */
    private $imageSize;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="integer")
     */
    public $room_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    public $room_description;

    /**
     * @ORM\Column(type="boolean")
     */
    public $is_popular;
    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

//    public function __toString()
//    {
//        return $this->id;
//    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function getRoomNumber(): ?int
    {
        return $this->room_number;
    }

    public function setRoomNumber(int $room_number): self
    {
        $this->room_number = $room_number;

        return $this;
    }

    public function getRoomDescription(): ?string
    {
        return $this->room_description;
    }

    public function setRoomDescription(string $room_description): self
    {
        $this->room_description = $room_description;

        return $this;
    }

    public function getIsPopular(): ?bool
    {
        return $this->is_popular;
    }

    public function setIsPopular(bool $is_popular): self
    {
        $this->is_popular = $is_popular;

        return $this;
    }
}

src/Form/RoomType.php
<?php

namespace App\Form;

use App\Entity\Room;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class RoomType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('room_name')
            ->add('room_price')
            ->add('room_person_amount')
            ->add('imageFile', VichImageType::class)
            ->add('availability')
            ->add('room_number')
            ->add('is_popular')
            ->add('room_description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Room::class,
        ]);
    }
}

src/Controller/RoomController.php
<?php

namespace App\Controller;

use App\Entity\Room;
use App\Entity\Booking;
use App\Form\RoomType;
use App\Repository\RoomRepository;
use App\Repository\BookingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/room")
 */
class RoomController extends AbstractController
{
    /**
     * @Route("/", name="room_index", methods={"GET"})
     */
    public function index(RoomRepository $roomRepository): Response
    {
        return $this->render('room/index.html.twig', [
            'rooms' => $roomRepository->findAll(),
        ]);
    }

    /**
     * @Route("/view", name="view_check", methods={"POST"})
     */
    public function checkDate()
    {
        $BeginDate = $_POST["BeginDate"];
        $EndDate = $_POST["EndDate"];

        $reservering = $this->getDoctrine()
            ->getRepository(Booking::class)
            ->getBetween(array($BeginDate, $EndDate));

        $input = array();
        for ($x = 0; $x < count($reservering); $x++) {
            array_push($input, $reservering[$x][1]);
        }

        $available = $this->getDoctrine()
            ->getRepository(Room::class)
            ->notIn($input);

        return $this->render('view/index.html.twig', [
            'room' => $available,
        ]);
    }


    /**
     * @Route("/new", name="room_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $room = new Room();
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($room);
            $entityManager->flush();

            return $this->redirectToRoute('room_index');
        }

        return $this->render('room/new.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_show", methods={"GET"})
     */
    public function show(Room $room): Response
    {
        return $this->render('room/show.html.twig', [
            'room' => $room,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="room_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Room $room): Response
    {
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('room_index', [
                'id' => $room->getId(),
            ]);
        }

        return $this->render('room/edit.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Room $room): Response
    {
        if ($this->isCsrfTokenValid('delete'.$room->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($room);
            $entityManager->flush();
        }

        return $this->redirectToRoute('room_index');
    }

//    /**
//     * @Route("/view", name="view_check", methods={"POST"})
//     */
//    public function checkDate()
//    {
//        $BeginDate = $_POST["BeginDate"];
//        $EndDate = $_POST["EndDate"];
//        echo $BeginDate;
//        echo $EndDate;
//        $reservering = $this->getDoctrine()
//            ->getRepository(view::class)
//            ->getBetween(array($BeginDate, $EndDate));
//
//        $input = array();
//        for ($x = 0; $x < count($reservering); $x++) {
//            array_push($input, $reservering[$x][1]);
//        }
//
//        $available = $this->getDoctrine()
//            ->getRepository(Room::class)
//            ->notIn($input);
//
//        return $this->render('kamer/index.html.twig', [
//            'kamers' => $available,
//        ]);
//    }
}

templates/room/_delete_form.html.twig
<form method="post" action="{{ path('room_delete', {'id': room.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ room.id) }}">
    <button class="btn">Delete</button>
</form>

templates/room/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/room/edit.html.twig
{% include 'base.html.twig' %}

{% block title %}Edit Room{% endblock %}

{% block body %}
    <h1>Edit Room</h1>

    {{ include('room/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('room_index') }}">back to list</a>

    {{ include('room/_delete_form.html.twig') }}
{% endblock %}

templates/room/index.html.twig
{% include 'base.html.twig' %}

{% block title %}Room index{% endblock %}

{% block body %}
    <h1>Room index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Room_name</th>
                <th>Room_price</th>
                <th>Room_person_amount</th>
                <th>Image name</th>
                <th>Availability</th>
                <th>Room_number</th>
                <th>Room_is popular</th>
                <th>Room_description</th>
            </tr>
        </thead>
        <tbody>
        {% for room in rooms %}
            <tr>
                <td>{{ room.id }}</td>
                <td>{{ room.roomName }}</td>
                <td>{{ room.roomPrice }}</td>
                <td>{{ room.roomPersonAmount }}</td>
                <td>{{ room.imageName }}</td>
                <td>{{ room.availability ? 'Yes' : 'No' }}</td>
                <td>{{ room.roomNumber }}</td>
                <td>{{ room.is_popular }}</td>
                <td>{{ room.roomDescription }}</td>
                <td>
                    <a href="{{ path('room_show', {'id': room.id}) }}">show</a>
                    <a href="{{ path('room_edit', {'id': room.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('room_new') }}">Create new</a>
{% endblock %}

templates/room/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Room{% endblock %}

{% block body %}
    <h1>Create new Room</h1>

    {{ include('room/_form.html.twig') }}

    <a href="{{ path('room_index') }}">back to list</a>
{% endblock %}

templates/room/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Room{% endblock %}

{% block body %}
    <h1>Room</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ room.id }}</td>
            </tr>
            <tr>
                <th>Room_name</th>
                <td>{{ room.roomName }}</td>
            </tr>
            <tr>
                <th>Room_price</th>
                <td>{{ room.roomPrice }}</td>
            </tr>
            <tr>
                <th>Room_person_amount</th>
                <td>{{ room.roomPersonAmount }}</td>
            </tr>
            <tr>
                <th>Availability</th>
                <td>{{ room.availability ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_popular</th>
                <td>{{ room.is_popular ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('room_index') }}">back to list</a>

    <a href="{{ path('room_edit', {'id': room.id}) }}">edit</a>

    {{ include('room/_delete_form.html.twig') }}
{% endblock %}